### ISSUE TITLE
Camel case not working in open type dialog

### ISSUE THREAD

**Issue by costin3141** [eclipse-jdt/eclipse.jdt.ui#2583]
Version: 2025-12 M1 (4.38.0 M1)
Build id: 20251009-0701

So, when opening the "open type"-dialog via ctrl+shift+T i usually search for a type via camel case (including some lower case letters). Since i installed today the new pre-release 2025-12 camel case is not working anymore. I could not figure out how they are treated as i get all kind of results but never ever something that would match the camel case.

Example: i have a type called "LoadUnitOrder" and LUO gives me (the letter between " are what eclipse shows in bold, matching my input)
LocalNames_"luo"
CurrencyNames_"luo"

For LU i get the following:

BestSo"lu"tionManager
"LU"ID
Labe"lU"i

As you can see, there does not seem to be a consistant rule on how the ide is applying my search pattern.

**Comment by iloveeclipse** [comment]
Please try with M2, there was a bug fixed in this area.

**Comment by costin3141** [comment]
Problem still exists in M2 even though not as much as before. Still broken example:
Class SupportFinderSimple 

Typing SupFS does not find it.
But SupFiS does NOT work.
SFS also works.

Very unlogical way this bug breaks camel case.

**Comment by costin3141** [comment]
I really do not want to sound like a di.. but don't you have a couple of junit tests in place or other automatic tests for the camel case functionallity? I mean i do not understand how this gets into master obviously so badly tested if tested at all. And that not only for the initial bug but now also for the fix.

Camel case is such a simple thing and easy to automatically test for. You might want to think about adding something to your test suit.
