### ISSUE TITLE
"Infer Generic Type Arguments..." with var leads to invalid code

### ISSUE THREAD

**Issue by Madjosz** [eclipse-jdt/eclipse.jdt.ui#774]
After fixing eclipse-jdt/eclipse.jdt.core#600 and already mentioned in #765 the quick fix "Infer Generic Type Arguments..." will produce invalid code when executed on a variable which was declared with `var`. Consider the following code
```java
package test1;
import java.util.List;
import java.util.ArrayList;

class E1 {
    void f() {
        var list = new ArrayList(); // (1)
        doSomethingWith(list);      // (2)
    }
    void doSomethingWith(List<Object> list) {}
}
```
We get the following warnings:
* `ArrayList` in (1): `ArrayList is a raw type. References to generic type ArrayList<E> should be parameterized`
* `list` in (2): `Type safety: The expression of type ArrayList needs unchecked conversion to conform to List<Object>`
and it offers the quick fix "Infer Generic Type Arguments..." which when executed results in the following code
```java
var<Object> list = new ArrayList<Object>();
```
which is invalid according to JLS and gives the error
`'var' cannot be used with type arguments`

On the other hand the provided quick fix on `ArrayList` "Add type arguments to 'ArrayList'" correctly changes to
```java
var list = new ArrayList<Object>();
```
but this is likely due to having only the `ArrayList` itself as target.

Without line (2) the quick fix "Infer Generic Type Arguments..." even does nothing.

While we are at it: Is there a special reason why this quickfix doesn't use the diamond operator on the RHS instead of duplicating the generics?

**Tested with**
Eclipse SDK
Version: 2023-12 (4.30)
Build id: I20230911-1800

openjdk version "20.0.2" 2023-07-18
OpenJDK Runtime Environment Temurin-20.0.2+9 (build 20.0.2+9)
OpenJDK 64-Bit Server VM Temurin-20.0.2+9 (build 20.0.2+9, mixed mode, sharing)

**Comment by jjohnstn** [comment]
This was fixed via #766

**Comment by Madjosz** [comment]
No, this bug is not fixed, #765 was about `org.eclipse.jdt.internal.corext.fix.Java50FixCore`, this issue is anout `org.eclipse.jdt.internal.corext.refactoring.generics.InferTypeArgumentsRefactoring`.
Problem is still present in latest Eclipse SDK Version: 2023-12 (4.30), Build id: I20230926-1800

**Comment by Madjosz** [comment]
Confirmed works in 2023-12 (4.30), build id: I20231018-0110
Thank you for your efforts!
